services:
  - type: web
    name: lulan-ml-api
    env: python
    region: oregon
    plan: free
    rootDir: server/ml-api
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
    healthCheckPath: /health
